FROM python:3.13.2-slim-bookworm
WORKDIR /fastapi
RUN pip install poetry
RUN pip install prometheus-fastapi-instrumentator
RUN apt-get update && apt-get install -y net-tools
RUN apt-get install -y curl
COPY poetry.lock pyproject.toml ./
RUN poetry config virtualenvs.create false
RUN poetry install
COPY . .
CMD ["poetry", "run", "uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]