apiVersion: v1
kind: Service
metadata:
  name: fastapi
  labels:
    app: fastapi
spec:
  type: ClusterIP
  selector:
      app: fastapi
  ports:
  - name: fastapi
    port: 8000
    targetPort: 8000
  - name: metrics
    port: 8000      # ✅ Change this from 9090 to 8000
    targetPort: 8000