prometheus-node-exporter:
  volumeMounts:
    - name: proc
      readOnly: true
      mountPath: /host/proc
    - name: sys
      readOnly: true
      mountPath: /host/sys
    - name: root
      readOnly: true
      mountPath: /host/root