apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      initContainers:
      - name: check-ollama
        image: busybox:latest
        command: ["bin/sh","-c"]
        args:
        - |
          until nc -zv ollama-service 11434; do
            echo "Waiting for ollama service ....."
            sleep 2
          done
      containers:
      - name: fastapi
        image: fastapi:latest-version
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi
spec:
  type: ClusterIP
  selector:
      app: fastapi
  ports:
  - name: fastapi
    port: 8000
    targetPort: 8000